version: '3'

services:
#  algod:
#    image: makerxau/algorand-sandbox-dev:latest
#    ports:
#      - "4001:4001"
#      - "4002:4002"
#      - "9392:9392"
  algod:
    image: wwinder/algod:latest
    ports:
      - "4001:8080"
    environment:
      - DEV_MODE
      - TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

